// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commitprocessor_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/domain/agent/entity"
)

// NewMockCommitProcessor creates a new instance of MockCommitProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitProcessor {
	mock := &MockCommitProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommitProcessor is an autogenerated mock type for the CommitProcessor type
type MockCommitProcessor struct {
	mock.Mock
}

type MockCommitProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitProcessor) EXPECT() *MockCommitProcessor_Expecter {
	return &MockCommitProcessor_Expecter{mock: &_m.Mock}
}

// GenCommitMessage provides a mock function for the type MockCommitProcessor
func (_mock *MockCommitProcessor) GenCommitMessage(context1 context.Context, commitData entity.CommitData) (string, error) {
	ret := _mock.Called(context1, commitData)

	if len(ret) == 0 {
		panic("no return value specified for GenCommitMessage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.CommitData) (string, error)); ok {
		return returnFunc(context1, commitData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.CommitData) string); ok {
		r0 = returnFunc(context1, commitData)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.CommitData) error); ok {
		r1 = returnFunc(context1, commitData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommitProcessor_GenCommitMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenCommitMessage'
type MockCommitProcessor_GenCommitMessage_Call struct {
	*mock.Call
}

// GenCommitMessage is a helper method to define mock.On call
//   - context1 context.Context
//   - commitData entity.CommitData
func (_e *MockCommitProcessor_Expecter) GenCommitMessage(context1 interface{}, commitData interface{}) *MockCommitProcessor_GenCommitMessage_Call {
	return &MockCommitProcessor_GenCommitMessage_Call{Call: _e.mock.On("GenCommitMessage", context1, commitData)}
}

func (_c *MockCommitProcessor_GenCommitMessage_Call) Run(run func(context1 context.Context, commitData entity.CommitData)) *MockCommitProcessor_GenCommitMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.CommitData
		if args[1] != nil {
			arg1 = args[1].(entity.CommitData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommitProcessor_GenCommitMessage_Call) Return(s string, err error) *MockCommitProcessor_GenCommitMessage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCommitProcessor_GenCommitMessage_Call) RunAndReturn(run func(context1 context.Context, commitData entity.CommitData) (string, error)) *MockCommitProcessor_GenCommitMessage_Call {
	_c.Call.Return(run)
	return _c
}
