// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filecontentprovider_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileContentProvider creates a new instance of MockFileContentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileContentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileContentProvider {
	mock := &MockFileContentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileContentProvider is an autogenerated mock type for the FileContentProvider type
type MockFileContentProvider struct {
	mock.Mock
}

type MockFileContentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileContentProvider) EXPECT() *MockFileContentProvider_Expecter {
	return &MockFileContentProvider_Expecter{mock: &_m.Mock}
}

// GetFileContent provides a mock function for the type MockFileContentProvider
func (_mock *MockFileContentProvider) GetFileContent(context1 context.Context, s string) ([]byte, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContent")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileContentProvider_GetFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContent'
type MockFileContentProvider_GetFileContent_Call struct {
	*mock.Call
}

// GetFileContent is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockFileContentProvider_Expecter) GetFileContent(context1 interface{}, s interface{}) *MockFileContentProvider_GetFileContent_Call {
	return &MockFileContentProvider_GetFileContent_Call{Call: _e.mock.On("GetFileContent", context1, s)}
}

func (_c *MockFileContentProvider_GetFileContent_Call) Run(run func(context1 context.Context, s string)) *MockFileContentProvider_GetFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileContentProvider_GetFileContent_Call) Return(bytes []byte, err error) *MockFileContentProvider_GetFileContent_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileContentProvider_GetFileContent_Call) RunAndReturn(run func(context1 context.Context, s string) ([]byte, error)) *MockFileContentProvider_GetFileContent_Call {
	_c.Call.Return(run)
	return _c
}
