// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package directoryreader_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/pkg/files"
)

// NewMockDirectoryReader creates a new instance of MockDirectoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectoryReader {
	mock := &MockDirectoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectoryReader is an autogenerated mock type for the DirectoryReader type
type MockDirectoryReader struct {
	mock.Mock
}

type MockDirectoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectoryReader) EXPECT() *MockDirectoryReader_Expecter {
	return &MockDirectoryReader_Expecter{mock: &_m.Mock}
}

// ReadFiles provides a mock function for the type MockDirectoryReader
func (_mock *MockDirectoryReader) ReadFiles(context1 context.Context, strings []string) (<-chan files.File, error) {
	ret := _mock.Called(context1, strings)

	if len(ret) == 0 {
		panic("no return value specified for ReadFiles")
	}

	var r0 <-chan files.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (<-chan files.File, error)); ok {
		return returnFunc(context1, strings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) <-chan files.File); ok {
		r0 = returnFunc(context1, strings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan files.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(context1, strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDirectoryReader_ReadFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFiles'
type MockDirectoryReader_ReadFiles_Call struct {
	*mock.Call
}

// ReadFiles is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
func (_e *MockDirectoryReader_Expecter) ReadFiles(context1 interface{}, strings interface{}) *MockDirectoryReader_ReadFiles_Call {
	return &MockDirectoryReader_ReadFiles_Call{Call: _e.mock.On("ReadFiles", context1, strings)}
}

func (_c *MockDirectoryReader_ReadFiles_Call) Run(run func(context1 context.Context, strings []string)) *MockDirectoryReader_ReadFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDirectoryReader_ReadFiles_Call) Return(fileCh <-chan files.File, err error) *MockDirectoryReader_ReadFiles_Call {
	_c.Call.Return(fileCh, err)
	return _c
}

func (_c *MockDirectoryReader_ReadFiles_Call) RunAndReturn(run func(context1 context.Context, strings []string) (<-chan files.File, error)) *MockDirectoryReader_ReadFiles_Call {
	_c.Call.Return(run)
	return _c
}
