// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package appbuilder_mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/pkg/factory"
)

// NewMockAppBuilder creates a new instance of MockAppBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppBuilder {
	mock := &MockAppBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppBuilder is an autogenerated mock type for the AppBuilder type
type MockAppBuilder struct {
	mock.Mock
}

type MockAppBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppBuilder) EXPECT() *MockAppBuilder_Expecter {
	return &MockAppBuilder_Expecter{mock: &_m.Mock}
}

// BuildApp provides a mock function for the type MockAppBuilder
func (_mock *MockAppBuilder) BuildApp(appFactory factory.AppFactory) (*factory.App, error) {
	ret := _mock.Called(appFactory)

	if len(ret) == 0 {
		panic("no return value specified for BuildApp")
	}

	var r0 *factory.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(factory.AppFactory) (*factory.App, error)); ok {
		return returnFunc(appFactory)
	}
	if returnFunc, ok := ret.Get(0).(func(factory.AppFactory) *factory.App); ok {
		r0 = returnFunc(appFactory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*factory.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(factory.AppFactory) error); ok {
		r1 = returnFunc(appFactory)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppBuilder_BuildApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildApp'
type MockAppBuilder_BuildApp_Call struct {
	*mock.Call
}

// BuildApp is a helper method to define mock.On call
//   - appFactory factory.AppFactory
func (_e *MockAppBuilder_Expecter) BuildApp(appFactory interface{}) *MockAppBuilder_BuildApp_Call {
	return &MockAppBuilder_BuildApp_Call{Call: _e.mock.On("BuildApp", appFactory)}
}

func (_c *MockAppBuilder_BuildApp_Call) Run(run func(appFactory factory.AppFactory)) *MockAppBuilder_BuildApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 factory.AppFactory
		if args[0] != nil {
			arg0 = args[0].(factory.AppFactory)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppBuilder_BuildApp_Call) Return(app *factory.App, err error) *MockAppBuilder_BuildApp_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockAppBuilder_BuildApp_Call) RunAndReturn(run func(appFactory factory.AppFactory) (*factory.App, error)) *MockAppBuilder_BuildApp_Call {
	_c.Call.Return(run)
	return _c
}
