// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package aiusecase_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAIUseCase creates a new instance of MockAIUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIUseCase {
	mock := &MockAIUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAIUseCase is an autogenerated mock type for the AIUseCase type
type MockAIUseCase struct {
	mock.Mock
}

type MockAIUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIUseCase) EXPECT() *MockAIUseCase_Expecter {
	return &MockAIUseCase_Expecter{mock: &_m.Mock}
}
