// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agentfactory_mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/domain/agent"
	"github.com/yaroslav-koval/hange/domain/auth"
)

// NewMockAgentFactory creates a new instance of MockAgentFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentFactory {
	mock := &MockAgentFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentFactory is an autogenerated mock type for the AgentFactory type
type MockAgentFactory struct {
	mock.Mock
}

type MockAgentFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentFactory) EXPECT() *MockAgentFactory_Expecter {
	return &MockAgentFactory_Expecter{mock: &_m.Mock}
}

// CreateCommitProcessor provides a mock function for the type MockAgentFactory
func (_mock *MockAgentFactory) CreateCommitProcessor(auth1 auth.Auth) (agent.CommitProcessor, error) {
	ret := _mock.Called(auth1)

	if len(ret) == 0 {
		panic("no return value specified for CreateCommitProcessor")
	}

	var r0 agent.CommitProcessor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.Auth) (agent.CommitProcessor, error)); ok {
		return returnFunc(auth1)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.Auth) agent.CommitProcessor); ok {
		r0 = returnFunc(auth1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(agent.CommitProcessor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(auth.Auth) error); ok {
		r1 = returnFunc(auth1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentFactory_CreateCommitProcessor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCommitProcessor'
type MockAgentFactory_CreateCommitProcessor_Call struct {
	*mock.Call
}

// CreateCommitProcessor is a helper method to define mock.On call
//   - auth1 auth.Auth
func (_e *MockAgentFactory_Expecter) CreateCommitProcessor(auth1 interface{}) *MockAgentFactory_CreateCommitProcessor_Call {
	return &MockAgentFactory_CreateCommitProcessor_Call{Call: _e.mock.On("CreateCommitProcessor", auth1)}
}

func (_c *MockAgentFactory_CreateCommitProcessor_Call) Run(run func(auth1 auth.Auth)) *MockAgentFactory_CreateCommitProcessor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.Auth
		if args[0] != nil {
			arg0 = args[0].(auth.Auth)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentFactory_CreateCommitProcessor_Call) Return(commitProcessor agent.CommitProcessor, err error) *MockAgentFactory_CreateCommitProcessor_Call {
	_c.Call.Return(commitProcessor, err)
	return _c
}

func (_c *MockAgentFactory_CreateCommitProcessor_Call) RunAndReturn(run func(auth1 auth.Auth) (agent.CommitProcessor, error)) *MockAgentFactory_CreateCommitProcessor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExplainProcessor provides a mock function for the type MockAgentFactory
func (_mock *MockAgentFactory) CreateExplainProcessor(auth1 auth.Auth) (agent.ExplainProcessor, error) {
	ret := _mock.Called(auth1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExplainProcessor")
	}

	var r0 agent.ExplainProcessor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.Auth) (agent.ExplainProcessor, error)); ok {
		return returnFunc(auth1)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.Auth) agent.ExplainProcessor); ok {
		r0 = returnFunc(auth1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(agent.ExplainProcessor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(auth.Auth) error); ok {
		r1 = returnFunc(auth1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentFactory_CreateExplainProcessor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExplainProcessor'
type MockAgentFactory_CreateExplainProcessor_Call struct {
	*mock.Call
}

// CreateExplainProcessor is a helper method to define mock.On call
//   - auth1 auth.Auth
func (_e *MockAgentFactory_Expecter) CreateExplainProcessor(auth1 interface{}) *MockAgentFactory_CreateExplainProcessor_Call {
	return &MockAgentFactory_CreateExplainProcessor_Call{Call: _e.mock.On("CreateExplainProcessor", auth1)}
}

func (_c *MockAgentFactory_CreateExplainProcessor_Call) Run(run func(auth1 auth.Auth)) *MockAgentFactory_CreateExplainProcessor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.Auth
		if args[0] != nil {
			arg0 = args[0].(auth.Auth)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentFactory_CreateExplainProcessor_Call) Return(explainProcessor agent.ExplainProcessor, err error) *MockAgentFactory_CreateExplainProcessor_Call {
	_c.Call.Return(explainProcessor, err)
	return _c
}

func (_c *MockAgentFactory_CreateExplainProcessor_Call) RunAndReturn(run func(auth1 auth.Auth) (agent.ExplainProcessor, error)) *MockAgentFactory_CreateExplainProcessor_Call {
	_c.Call.Return(run)
	return _c
}
