// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package changes_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChanges creates a new instance of MockChanges. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChanges(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChanges {
	mock := &MockChanges{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChanges is an autogenerated mock type for the Changes type
type MockChanges struct {
	mock.Mock
}

type MockChanges_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChanges) EXPECT() *MockChanges_Expecter {
	return &MockChanges_Expecter{mock: &_m.Mock}
}

// StagedDiff provides a mock function for the type MockChanges
func (_mock *MockChanges) StagedDiff(ctx context.Context, linesAround int) (string, error) {
	ret := _mock.Called(ctx, linesAround)

	if len(ret) == 0 {
		panic("no return value specified for StagedDiff")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, linesAround)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, linesAround)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, linesAround)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChanges_StagedDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StagedDiff'
type MockChanges_StagedDiff_Call struct {
	*mock.Call
}

// StagedDiff is a helper method to define mock.On call
//   - ctx context.Context
//   - linesAround int
func (_e *MockChanges_Expecter) StagedDiff(ctx interface{}, linesAround interface{}) *MockChanges_StagedDiff_Call {
	return &MockChanges_StagedDiff_Call{Call: _e.mock.On("StagedDiff", ctx, linesAround)}
}

func (_c *MockChanges_StagedDiff_Call) Run(run func(ctx context.Context, linesAround int)) *MockChanges_StagedDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChanges_StagedDiff_Call) Return(s string, err error) *MockChanges_StagedDiff_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChanges_StagedDiff_Call) RunAndReturn(run func(ctx context.Context, linesAround int) (string, error)) *MockChanges_StagedDiff_Call {
	_c.Call.Return(run)
	return _c
}

// StagedStatus provides a mock function for the type MockChanges
func (_mock *MockChanges) StagedStatus(context1 context.Context) (string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for StagedStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChanges_StagedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StagedStatus'
type MockChanges_StagedStatus_Call struct {
	*mock.Call
}

// StagedStatus is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockChanges_Expecter) StagedStatus(context1 interface{}) *MockChanges_StagedStatus_Call {
	return &MockChanges_StagedStatus_Call{Call: _e.mock.On("StagedStatus", context1)}
}

func (_c *MockChanges_StagedStatus_Call) Run(run func(context1 context.Context)) *MockChanges_StagedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChanges_StagedStatus_Call) Return(s string, err error) *MockChanges_StagedStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChanges_StagedStatus_Call) RunAndReturn(run func(context1 context.Context) (string, error)) *MockChanges_StagedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockChanges
func (_mock *MockChanges) Status(context1 context.Context) (string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChanges_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockChanges_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockChanges_Expecter) Status(context1 interface{}) *MockChanges_Status_Call {
	return &MockChanges_Status_Call{Call: _e.mock.On("Status", context1)}
}

func (_c *MockChanges_Status_Call) Run(run func(context1 context.Context)) *MockChanges_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChanges_Status_Call) Return(s string, err error) *MockChanges_Status_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChanges_Status_Call) RunAndReturn(run func(context1 context.Context) (string, error)) *MockChanges_Status_Call {
	_c.Call.Return(run)
	return _c
}
