// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package configurator_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigurator creates a new instance of MockConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurator {
	mock := &MockConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigurator is an autogenerated mock type for the Configurator type
type MockConfigurator struct {
	mock.Mock
}

type MockConfigurator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurator) EXPECT() *MockConfigurator_Expecter {
	return &MockConfigurator_Expecter{mock: &_m.Mock}
}

// ReadField provides a mock function for the type MockConfigurator
func (_mock *MockConfigurator) ReadField(field string) any {
	ret := _mock.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for ReadField")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(field)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockConfigurator_ReadField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadField'
type MockConfigurator_ReadField_Call struct {
	*mock.Call
}

// ReadField is a helper method to define mock.On call
//   - field string
func (_e *MockConfigurator_Expecter) ReadField(field interface{}) *MockConfigurator_ReadField_Call {
	return &MockConfigurator_ReadField_Call{Call: _e.mock.On("ReadField", field)}
}

func (_c *MockConfigurator_ReadField_Call) Run(run func(field string)) *MockConfigurator_ReadField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurator_ReadField_Call) Return(v any) *MockConfigurator_ReadField_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConfigurator_ReadField_Call) RunAndReturn(run func(field string) any) *MockConfigurator_ReadField_Call {
	_c.Call.Return(run)
	return _c
}

// WriteField provides a mock function for the type MockConfigurator
func (_mock *MockConfigurator) WriteField(field string, value any) error {
	ret := _mock.Called(field, value)

	if len(ret) == 0 {
		panic("no return value specified for WriteField")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(field, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigurator_WriteField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteField'
type MockConfigurator_WriteField_Call struct {
	*mock.Call
}

// WriteField is a helper method to define mock.On call
//   - field string
//   - value any
func (_e *MockConfigurator_Expecter) WriteField(field interface{}, value interface{}) *MockConfigurator_WriteField_Call {
	return &MockConfigurator_WriteField_Call{Call: _e.mock.On("WriteField", field, value)}
}

func (_c *MockConfigurator_WriteField_Call) Run(run func(field string, value any)) *MockConfigurator_WriteField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurator_WriteField_Call) Return(err error) *MockConfigurator_WriteField_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigurator_WriteField_Call) RunAndReturn(run func(field string, value any) error) *MockConfigurator_WriteField_Call {
	_c.Call.Return(run)
	return _c
}
