// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package changesprovider_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChangesProvider creates a new instance of MockChangesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChangesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChangesProvider {
	mock := &MockChangesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChangesProvider is an autogenerated mock type for the ChangesProvider type
type MockChangesProvider struct {
	mock.Mock
}

type MockChangesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChangesProvider) EXPECT() *MockChangesProvider_Expecter {
	return &MockChangesProvider_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockChangesProvider
func (_mock *MockChangesProvider) Commit(ctx context.Context, message string) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChangesProvider_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockChangesProvider_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *MockChangesProvider_Expecter) Commit(ctx interface{}, message interface{}) *MockChangesProvider_Commit_Call {
	return &MockChangesProvider_Commit_Call{Call: _e.mock.On("Commit", ctx, message)}
}

func (_c *MockChangesProvider_Commit_Call) Run(run func(ctx context.Context, message string)) *MockChangesProvider_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChangesProvider_Commit_Call) Return(err error) *MockChangesProvider_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChangesProvider_Commit_Call) RunAndReturn(run func(ctx context.Context, message string) error) *MockChangesProvider_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// StagedDiff provides a mock function for the type MockChangesProvider
func (_mock *MockChangesProvider) StagedDiff(ctx context.Context, linesAround int) (string, error) {
	ret := _mock.Called(ctx, linesAround)

	if len(ret) == 0 {
		panic("no return value specified for StagedDiff")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, linesAround)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, linesAround)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, linesAround)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChangesProvider_StagedDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StagedDiff'
type MockChangesProvider_StagedDiff_Call struct {
	*mock.Call
}

// StagedDiff is a helper method to define mock.On call
//   - ctx context.Context
//   - linesAround int
func (_e *MockChangesProvider_Expecter) StagedDiff(ctx interface{}, linesAround interface{}) *MockChangesProvider_StagedDiff_Call {
	return &MockChangesProvider_StagedDiff_Call{Call: _e.mock.On("StagedDiff", ctx, linesAround)}
}

func (_c *MockChangesProvider_StagedDiff_Call) Run(run func(ctx context.Context, linesAround int)) *MockChangesProvider_StagedDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChangesProvider_StagedDiff_Call) Return(s string, err error) *MockChangesProvider_StagedDiff_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChangesProvider_StagedDiff_Call) RunAndReturn(run func(ctx context.Context, linesAround int) (string, error)) *MockChangesProvider_StagedDiff_Call {
	_c.Call.Return(run)
	return _c
}

// StagedStatus provides a mock function for the type MockChangesProvider
func (_mock *MockChangesProvider) StagedStatus(context1 context.Context) (string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for StagedStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChangesProvider_StagedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StagedStatus'
type MockChangesProvider_StagedStatus_Call struct {
	*mock.Call
}

// StagedStatus is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockChangesProvider_Expecter) StagedStatus(context1 interface{}) *MockChangesProvider_StagedStatus_Call {
	return &MockChangesProvider_StagedStatus_Call{Call: _e.mock.On("StagedStatus", context1)}
}

func (_c *MockChangesProvider_StagedStatus_Call) Run(run func(context1 context.Context)) *MockChangesProvider_StagedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChangesProvider_StagedStatus_Call) Return(s string, err error) *MockChangesProvider_StagedStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChangesProvider_StagedStatus_Call) RunAndReturn(run func(context1 context.Context) (string, error)) *MockChangesProvider_StagedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockChangesProvider
func (_mock *MockChangesProvider) Status(context1 context.Context) (string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChangesProvider_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockChangesProvider_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockChangesProvider_Expecter) Status(context1 interface{}) *MockChangesProvider_Status_Call {
	return &MockChangesProvider_Status_Call{Call: _e.mock.On("Status", context1)}
}

func (_c *MockChangesProvider_Status_Call) Run(run func(context1 context.Context)) *MockChangesProvider_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChangesProvider_Status_Call) Return(s string, err error) *MockChangesProvider_Status_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChangesProvider_Status_Call) RunAndReturn(run func(context1 context.Context) (string, error)) *MockChangesProvider_Status_Call {
	_c.Call.Return(run)
	return _c
}
