// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package aiagent_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/pkg/agent"
)

// NewMockAIAgent creates a new instance of MockAIAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIAgent {
	mock := &MockAIAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAIAgent is an autogenerated mock type for the AIAgent type
type MockAIAgent struct {
	mock.Mock
}

type MockAIAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIAgent) EXPECT() *MockAIAgent_Expecter {
	return &MockAIAgent_Expecter{mock: &_m.Mock}
}

// ExplainFiles provides a mock function for the type MockAIAgent
func (_mock *MockAIAgent) ExplainFiles(ctx context.Context, files <-chan agent.File) (string, error) {
	ret := _mock.Called(ctx, files)

	if len(ret) == 0 {
		panic("no return value specified for ExplainFiles")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, <-chan agent.File) (string, error)); ok {
		return returnFunc(ctx, files)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, <-chan agent.File) string); ok {
		r0 = returnFunc(ctx, files)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, <-chan agent.File) error); ok {
		r1 = returnFunc(ctx, files)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIAgent_ExplainFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExplainFiles'
type MockAIAgent_ExplainFiles_Call struct {
	*mock.Call
}

// ExplainFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - files <-chan agent.File
func (_e *MockAIAgent_Expecter) ExplainFiles(ctx interface{}, files interface{}) *MockAIAgent_ExplainFiles_Call {
	return &MockAIAgent_ExplainFiles_Call{Call: _e.mock.On("ExplainFiles", ctx, files)}
}

func (_c *MockAIAgent_ExplainFiles_Call) Run(run func(ctx context.Context, files <-chan agent.File)) *MockAIAgent_ExplainFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 <-chan agent.File
		if args[1] != nil {
			arg1 = args[1].(<-chan agent.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAIAgent_ExplainFiles_Call) Return(s string, err error) *MockAIAgent_ExplainFiles_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAIAgent_ExplainFiles_Call) RunAndReturn(run func(ctx context.Context, files <-chan agent.File) (string, error)) *MockAIAgent_ExplainFiles_Call {
	_c.Call.Return(run)
	return _c
}
