// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package explainprocessor_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/domain/entities"
)

// NewMockExplainProcessor creates a new instance of MockExplainProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExplainProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExplainProcessor {
	mock := &MockExplainProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExplainProcessor is an autogenerated mock type for the ExplainProcessor type
type MockExplainProcessor struct {
	mock.Mock
}

type MockExplainProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExplainProcessor) EXPECT() *MockExplainProcessor_Expecter {
	return &MockExplainProcessor_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type MockExplainProcessor
func (_mock *MockExplainProcessor) Cleanup(context1 context.Context) {
	_mock.Called(context1)
	return
}

// MockExplainProcessor_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockExplainProcessor_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockExplainProcessor_Expecter) Cleanup(context1 interface{}) *MockExplainProcessor_Cleanup_Call {
	return &MockExplainProcessor_Cleanup_Call{Call: _e.mock.On("Cleanup", context1)}
}

func (_c *MockExplainProcessor_Cleanup_Call) Run(run func(context1 context.Context)) *MockExplainProcessor_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExplainProcessor_Cleanup_Call) Return() *MockExplainProcessor_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExplainProcessor_Cleanup_Call) RunAndReturn(run func(context1 context.Context)) *MockExplainProcessor_Cleanup_Call {
	_c.Run(run)
	return _c
}

// ExecuteExplainRequest provides a mock function for the type MockExplainProcessor
func (_mock *MockExplainProcessor) ExecuteExplainRequest(context1 context.Context) (string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteExplainRequest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExplainProcessor_ExecuteExplainRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteExplainRequest'
type MockExplainProcessor_ExecuteExplainRequest_Call struct {
	*mock.Call
}

// ExecuteExplainRequest is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockExplainProcessor_Expecter) ExecuteExplainRequest(context1 interface{}) *MockExplainProcessor_ExecuteExplainRequest_Call {
	return &MockExplainProcessor_ExecuteExplainRequest_Call{Call: _e.mock.On("ExecuteExplainRequest", context1)}
}

func (_c *MockExplainProcessor_ExecuteExplainRequest_Call) Run(run func(context1 context.Context)) *MockExplainProcessor_ExecuteExplainRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExplainProcessor_ExecuteExplainRequest_Call) Return(s string, err error) *MockExplainProcessor_ExecuteExplainRequest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockExplainProcessor_ExecuteExplainRequest_Call) RunAndReturn(run func(context1 context.Context) (string, error)) *MockExplainProcessor_ExecuteExplainRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessFiles provides a mock function for the type MockExplainProcessor
func (_mock *MockExplainProcessor) ProcessFiles(context1 context.Context, fileCh <-chan entities.File) error {
	ret := _mock.Called(context1, fileCh)

	if len(ret) == 0 {
		panic("no return value specified for ProcessFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, <-chan entities.File) error); ok {
		r0 = returnFunc(context1, fileCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExplainProcessor_ProcessFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessFiles'
type MockExplainProcessor_ProcessFiles_Call struct {
	*mock.Call
}

// ProcessFiles is a helper method to define mock.On call
//   - context1 context.Context
//   - fileCh <-chan entities.File
func (_e *MockExplainProcessor_Expecter) ProcessFiles(context1 interface{}, fileCh interface{}) *MockExplainProcessor_ProcessFiles_Call {
	return &MockExplainProcessor_ProcessFiles_Call{Call: _e.mock.On("ProcessFiles", context1, fileCh)}
}

func (_c *MockExplainProcessor_ProcessFiles_Call) Run(run func(context1 context.Context, fileCh <-chan entities.File)) *MockExplainProcessor_ProcessFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 <-chan entities.File
		if args[1] != nil {
			arg1 = args[1].(<-chan entities.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExplainProcessor_ProcessFiles_Call) Return(err error) *MockExplainProcessor_ProcessFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExplainProcessor_ProcessFiles_Call) RunAndReturn(run func(context1 context.Context, fileCh <-chan entities.File) error) *MockExplainProcessor_ProcessFiles_Call {
	_c.Call.Return(run)
	return _c
}
