// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commandexecutor_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockcommandExecutor creates a new instance of mockcommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcommandExecutor {
	mock := &mockcommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcommandExecutor is an autogenerated mock type for the commandExecutor type
type mockcommandExecutor struct {
	mock.Mock
}

type mockcommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcommandExecutor) EXPECT() *mockcommandExecutor_Expecter {
	return &mockcommandExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type mockcommandExecutor
func (_mock *mockcommandExecutor) Execute(context1 context.Context, s string) (string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcommandExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockcommandExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *mockcommandExecutor_Expecter) Execute(context1 interface{}, s interface{}) *mockcommandExecutor_Execute_Call {
	return &mockcommandExecutor_Execute_Call{Call: _e.mock.On("Execute", context1, s)}
}

func (_c *mockcommandExecutor_Execute_Call) Run(run func(context1 context.Context, s string)) *mockcommandExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcommandExecutor_Execute_Call) Return(s1 string, err error) *mockcommandExecutor_Execute_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *mockcommandExecutor_Execute_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *mockcommandExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}
