// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commandexecutor_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Output provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) Output(context1 context.Context, s string, strings ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(strings) > 0 {
		tmpRet = _mock.Called(context1, s, strings)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return returnFunc(context1, s, strings...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = returnFunc(context1, s, strings...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(context1, s, strings...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandExecutor_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type MockCommandExecutor_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - strings ...string
func (_e *MockCommandExecutor_Expecter) Output(context1 interface{}, s interface{}, strings ...interface{}) *MockCommandExecutor_Output_Call {
	return &MockCommandExecutor_Output_Call{Call: _e.mock.On("Output",
		append([]interface{}{context1, s}, strings...)...)}
}

func (_c *MockCommandExecutor_Output_Call) Run(run func(context1 context.Context, s string, strings ...string)) *MockCommandExecutor_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_Output_Call) Return(s1 string, err error) *MockCommandExecutor_Output_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockCommandExecutor_Output_Call) RunAndReturn(run func(context1 context.Context, s string, strings ...string) (string, error)) *MockCommandExecutor_Output_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) Run(context1 context.Context, s string, strings ...string) error {
	var tmpRet mock.Arguments
	if len(strings) > 0 {
		tmpRet = _mock.Called(context1, s, strings)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(context1, s, strings...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommandExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - strings ...string
func (_e *MockCommandExecutor_Expecter) Run(context1 interface{}, s interface{}, strings ...interface{}) *MockCommandExecutor_Run_Call {
	return &MockCommandExecutor_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{context1, s}, strings...)...)}
}

func (_c *MockCommandExecutor_Run_Call) Run(run func(context1 context.Context, s string, strings ...string)) *MockCommandExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_Run_Call) Return(err error) *MockCommandExecutor_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandExecutor_Run_Call) RunAndReturn(run func(context1 context.Context, s string, strings ...string) error) *MockCommandExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}
