// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type MockAuth
func (_mock *MockAuth) GetToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockAuth_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *MockAuth_Expecter) GetToken() *MockAuth_GetToken_Call {
	return &MockAuth_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *MockAuth_GetToken_Call) Run(run func()) *MockAuth_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuth_GetToken_Call) Return(s string, err error) *MockAuth_GetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuth_GetToken_Call) RunAndReturn(run func() (string, error)) *MockAuth_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type MockAuth
func (_mock *MockAuth) SaveToken(authToken string) error {
	ret := _mock.Called(authToken)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(authToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuth_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockAuth_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - authToken string
func (_e *MockAuth_Expecter) SaveToken(authToken interface{}) *MockAuth_SaveToken_Call {
	return &MockAuth_SaveToken_Call{Call: _e.mock.On("SaveToken", authToken)}
}

func (_c *MockAuth_SaveToken_Call) Run(run func(authToken string)) *MockAuth_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuth_SaveToken_Call) Return(err error) *MockAuth_SaveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuth_SaveToken_Call) RunAndReturn(run func(authToken string) error) *MockAuth_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}
