// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tokenstorer_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenStorer creates a new instance of MockTokenStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStorer {
	mock := &MockTokenStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenStorer is an autogenerated mock type for the TokenStorer type
type MockTokenStorer struct {
	mock.Mock
}

type MockTokenStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStorer) EXPECT() *MockTokenStorer_Expecter {
	return &MockTokenStorer_Expecter{mock: &_m.Mock}
}

// Store provides a mock function for the type MockTokenStorer
func (_mock *MockTokenStorer) Store(token string) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStorer_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockTokenStorer_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - token string
func (_e *MockTokenStorer_Expecter) Store(token interface{}) *MockTokenStorer_Store_Call {
	return &MockTokenStorer_Store_Call{Call: _e.mock.On("Store", token)}
}

func (_c *MockTokenStorer_Store_Call) Run(run func(token string)) *MockTokenStorer_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenStorer_Store_Call) Return(err error) *MockTokenStorer_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStorer_Store_Call) RunAndReturn(run func(token string) error) *MockTokenStorer_Store_Call {
	_c.Call.Return(run)
	return _c
}
