// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filenamesprovider_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileNamesProvider creates a new instance of MockFileNamesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileNamesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileNamesProvider {
	mock := &MockFileNamesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileNamesProvider is an autogenerated mock type for the FileNamesProvider type
type MockFileNamesProvider struct {
	mock.Mock
}

type MockFileNamesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileNamesProvider) EXPECT() *MockFileNamesProvider_Expecter {
	return &MockFileNamesProvider_Expecter{mock: &_m.Mock}
}

// GetAllFileNames provides a mock function for the type MockFileNamesProvider
func (_mock *MockFileNamesProvider) GetAllFileNames(context1 context.Context, strings []string) ([]string, error) {
	ret := _mock.Called(context1, strings)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFileNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(context1, strings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(context1, strings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(context1, strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileNamesProvider_GetAllFileNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFileNames'
type MockFileNamesProvider_GetAllFileNames_Call struct {
	*mock.Call
}

// GetAllFileNames is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
func (_e *MockFileNamesProvider_Expecter) GetAllFileNames(context1 interface{}, strings interface{}) *MockFileNamesProvider_GetAllFileNames_Call {
	return &MockFileNamesProvider_GetAllFileNames_Call{Call: _e.mock.On("GetAllFileNames", context1, strings)}
}

func (_c *MockFileNamesProvider_GetAllFileNames_Call) Run(run func(context1 context.Context, strings []string)) *MockFileNamesProvider_GetAllFileNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileNamesProvider_GetAllFileNames_Call) Return(strings1 []string, err error) *MockFileNamesProvider_GetAllFileNames_Call {
	_c.Call.Return(strings1, err)
	return _c
}

func (_c *MockFileNamesProvider_GetAllFileNames_Call) RunAndReturn(run func(context1 context.Context, strings []string) ([]string, error)) *MockFileNamesProvider_GetAllFileNames_Call {
	_c.Call.Return(run)
	return _c
}
