// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tokenfetcher_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenFetcher creates a new instance of MockTokenFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenFetcher {
	mock := &MockTokenFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenFetcher is an autogenerated mock type for the TokenFetcher type
type MockTokenFetcher struct {
	mock.Mock
}

type MockTokenFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenFetcher) EXPECT() *MockTokenFetcher_Expecter {
	return &MockTokenFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockTokenFetcher
func (_mock *MockTokenFetcher) Fetch() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockTokenFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
func (_e *MockTokenFetcher_Expecter) Fetch() *MockTokenFetcher_Fetch_Call {
	return &MockTokenFetcher_Fetch_Call{Call: _e.mock.On("Fetch")}
}

func (_c *MockTokenFetcher_Fetch_Call) Run(run func()) *MockTokenFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenFetcher_Fetch_Call) Return(s string, err error) *MockTokenFetcher_Fetch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenFetcher_Fetch_Call) RunAndReturn(run func() (string, error)) *MockTokenFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
