// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fileerrormapper_mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileErrorMapper creates a new instance of MockFileErrorMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileErrorMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileErrorMapper {
	mock := &MockFileErrorMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileErrorMapper is an autogenerated mock type for the FileErrorMapper type
type MockFileErrorMapper struct {
	mock.Mock
}

type MockFileErrorMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileErrorMapper) EXPECT() *MockFileErrorMapper_Expecter {
	return &MockFileErrorMapper_Expecter{mock: &_m.Mock}
}

// Map provides a mock function for the type MockFileErrorMapper
func (_mock *MockFileErrorMapper) Map(err error) error {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for Map")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(error) error); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileErrorMapper_Map_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Map'
type MockFileErrorMapper_Map_Call struct {
	*mock.Call
}

// Map is a helper method to define mock.On call
//   - err error
func (_e *MockFileErrorMapper_Expecter) Map(err interface{}) *MockFileErrorMapper_Map_Call {
	return &MockFileErrorMapper_Map_Call{Call: _e.mock.On("Map", err)}
}

func (_c *MockFileErrorMapper_Map_Call) Run(run func(err error)) *MockFileErrorMapper_Map_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileErrorMapper_Map_Call) Return(err1 error) *MockFileErrorMapper_Map_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockFileErrorMapper_Map_Call) RunAndReturn(run func(err error) error) *MockFileErrorMapper_Map_Call {
	_c.Call.Return(run)
	return _c
}
