// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package appfactory_mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/yaroslav-koval/hange/pkg/auth"
	"github.com/yaroslav-koval/hange/pkg/config"
	"github.com/yaroslav-koval/hange/pkg/crypt"
	"github.com/yaroslav-koval/hange/pkg/fileprovider"
	"github.com/yaroslav-koval/hange/pkg/git"
)

// NewMockAppFactory creates a new instance of MockAppFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppFactory {
	mock := &MockAppFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppFactory is an autogenerated mock type for the AppFactory type
type MockAppFactory struct {
	mock.Mock
}

type MockAppFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppFactory) EXPECT() *MockAppFactory_Expecter {
	return &MockAppFactory_Expecter{mock: &_m.Mock}
}

// CreateBase64Decryptor provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateBase64Decryptor() (crypt.Decryptor, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateBase64Decryptor")
	}

	var r0 crypt.Decryptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (crypt.Decryptor, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() crypt.Decryptor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypt.Decryptor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateBase64Decryptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBase64Decryptor'
type MockAppFactory_CreateBase64Decryptor_Call struct {
	*mock.Call
}

// CreateBase64Decryptor is a helper method to define mock.On call
func (_e *MockAppFactory_Expecter) CreateBase64Decryptor() *MockAppFactory_CreateBase64Decryptor_Call {
	return &MockAppFactory_CreateBase64Decryptor_Call{Call: _e.mock.On("CreateBase64Decryptor")}
}

func (_c *MockAppFactory_CreateBase64Decryptor_Call) Run(run func()) *MockAppFactory_CreateBase64Decryptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppFactory_CreateBase64Decryptor_Call) Return(decryptor crypt.Decryptor, err error) *MockAppFactory_CreateBase64Decryptor_Call {
	_c.Call.Return(decryptor, err)
	return _c
}

func (_c *MockAppFactory_CreateBase64Decryptor_Call) RunAndReturn(run func() (crypt.Decryptor, error)) *MockAppFactory_CreateBase64Decryptor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBase64Encryptor provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateBase64Encryptor() (crypt.Encryptor, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateBase64Encryptor")
	}

	var r0 crypt.Encryptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (crypt.Encryptor, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() crypt.Encryptor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypt.Encryptor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateBase64Encryptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBase64Encryptor'
type MockAppFactory_CreateBase64Encryptor_Call struct {
	*mock.Call
}

// CreateBase64Encryptor is a helper method to define mock.On call
func (_e *MockAppFactory_Expecter) CreateBase64Encryptor() *MockAppFactory_CreateBase64Encryptor_Call {
	return &MockAppFactory_CreateBase64Encryptor_Call{Call: _e.mock.On("CreateBase64Encryptor")}
}

func (_c *MockAppFactory_CreateBase64Encryptor_Call) Run(run func()) *MockAppFactory_CreateBase64Encryptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppFactory_CreateBase64Encryptor_Call) Return(encryptor crypt.Encryptor, err error) *MockAppFactory_CreateBase64Encryptor_Call {
	_c.Call.Return(encryptor, err)
	return _c
}

func (_c *MockAppFactory_CreateBase64Encryptor_Call) RunAndReturn(run func() (crypt.Encryptor, error)) *MockAppFactory_CreateBase64Encryptor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConfigurator provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateConfigurator() (config.Configurator, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateConfigurator")
	}

	var r0 config.Configurator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (config.Configurator, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() config.Configurator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Configurator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateConfigurator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConfigurator'
type MockAppFactory_CreateConfigurator_Call struct {
	*mock.Call
}

// CreateConfigurator is a helper method to define mock.On call
func (_e *MockAppFactory_Expecter) CreateConfigurator() *MockAppFactory_CreateConfigurator_Call {
	return &MockAppFactory_CreateConfigurator_Call{Call: _e.mock.On("CreateConfigurator")}
}

func (_c *MockAppFactory_CreateConfigurator_Call) Run(run func()) *MockAppFactory_CreateConfigurator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppFactory_CreateConfigurator_Call) Return(configurator config.Configurator, err error) *MockAppFactory_CreateConfigurator_Call {
	_c.Call.Return(configurator, err)
	return _c
}

func (_c *MockAppFactory_CreateConfigurator_Call) RunAndReturn(run func() (config.Configurator, error)) *MockAppFactory_CreateConfigurator_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFileProvider provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateFileProvider() (fileprovider.FileProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateFileProvider")
	}

	var r0 fileprovider.FileProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (fileprovider.FileProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() fileprovider.FileProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fileprovider.FileProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateFileProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFileProvider'
type MockAppFactory_CreateFileProvider_Call struct {
	*mock.Call
}

// CreateFileProvider is a helper method to define mock.On call
func (_e *MockAppFactory_Expecter) CreateFileProvider() *MockAppFactory_CreateFileProvider_Call {
	return &MockAppFactory_CreateFileProvider_Call{Call: _e.mock.On("CreateFileProvider")}
}

func (_c *MockAppFactory_CreateFileProvider_Call) Run(run func()) *MockAppFactory_CreateFileProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppFactory_CreateFileProvider_Call) Return(fileProvider fileprovider.FileProvider, err error) *MockAppFactory_CreateFileProvider_Call {
	_c.Call.Return(fileProvider, err)
	return _c
}

func (_c *MockAppFactory_CreateFileProvider_Call) RunAndReturn(run func() (fileprovider.FileProvider, error)) *MockAppFactory_CreateFileProvider_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGitChangesProvider provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateGitChangesProvider() (git.ChangesProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateGitChangesProvider")
	}

	var r0 git.ChangesProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (git.ChangesProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() git.ChangesProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(git.ChangesProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateGitChangesProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGitChangesProvider'
type MockAppFactory_CreateGitChangesProvider_Call struct {
	*mock.Call
}

// CreateGitChangesProvider is a helper method to define mock.On call
func (_e *MockAppFactory_Expecter) CreateGitChangesProvider() *MockAppFactory_CreateGitChangesProvider_Call {
	return &MockAppFactory_CreateGitChangesProvider_Call{Call: _e.mock.On("CreateGitChangesProvider")}
}

func (_c *MockAppFactory_CreateGitChangesProvider_Call) Run(run func()) *MockAppFactory_CreateGitChangesProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppFactory_CreateGitChangesProvider_Call) Return(changesProvider git.ChangesProvider, err error) *MockAppFactory_CreateGitChangesProvider_Call {
	_c.Call.Return(changesProvider, err)
	return _c
}

func (_c *MockAppFactory_CreateGitChangesProvider_Call) RunAndReturn(run func() (git.ChangesProvider, error)) *MockAppFactory_CreateGitChangesProvider_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTokenFetcher provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateTokenFetcher(configurator config.Configurator) (auth.TokenFetcher, error) {
	ret := _mock.Called(configurator)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenFetcher")
	}

	var r0 auth.TokenFetcher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(config.Configurator) (auth.TokenFetcher, error)); ok {
		return returnFunc(configurator)
	}
	if returnFunc, ok := ret.Get(0).(func(config.Configurator) auth.TokenFetcher); ok {
		r0 = returnFunc(configurator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.TokenFetcher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(config.Configurator) error); ok {
		r1 = returnFunc(configurator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateTokenFetcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenFetcher'
type MockAppFactory_CreateTokenFetcher_Call struct {
	*mock.Call
}

// CreateTokenFetcher is a helper method to define mock.On call
//   - configurator config.Configurator
func (_e *MockAppFactory_Expecter) CreateTokenFetcher(configurator interface{}) *MockAppFactory_CreateTokenFetcher_Call {
	return &MockAppFactory_CreateTokenFetcher_Call{Call: _e.mock.On("CreateTokenFetcher", configurator)}
}

func (_c *MockAppFactory_CreateTokenFetcher_Call) Run(run func(configurator config.Configurator)) *MockAppFactory_CreateTokenFetcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Configurator
		if args[0] != nil {
			arg0 = args[0].(config.Configurator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppFactory_CreateTokenFetcher_Call) Return(tokenFetcher auth.TokenFetcher, err error) *MockAppFactory_CreateTokenFetcher_Call {
	_c.Call.Return(tokenFetcher, err)
	return _c
}

func (_c *MockAppFactory_CreateTokenFetcher_Call) RunAndReturn(run func(configurator config.Configurator) (auth.TokenFetcher, error)) *MockAppFactory_CreateTokenFetcher_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTokenStorer provides a mock function for the type MockAppFactory
func (_mock *MockAppFactory) CreateTokenStorer(configurator config.Configurator) (auth.TokenStorer, error) {
	ret := _mock.Called(configurator)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenStorer")
	}

	var r0 auth.TokenStorer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(config.Configurator) (auth.TokenStorer, error)); ok {
		return returnFunc(configurator)
	}
	if returnFunc, ok := ret.Get(0).(func(config.Configurator) auth.TokenStorer); ok {
		r0 = returnFunc(configurator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.TokenStorer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(config.Configurator) error); ok {
		r1 = returnFunc(configurator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppFactory_CreateTokenStorer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenStorer'
type MockAppFactory_CreateTokenStorer_Call struct {
	*mock.Call
}

// CreateTokenStorer is a helper method to define mock.On call
//   - configurator config.Configurator
func (_e *MockAppFactory_Expecter) CreateTokenStorer(configurator interface{}) *MockAppFactory_CreateTokenStorer_Call {
	return &MockAppFactory_CreateTokenStorer_Call{Call: _e.mock.On("CreateTokenStorer", configurator)}
}

func (_c *MockAppFactory_CreateTokenStorer_Call) Run(run func(configurator config.Configurator)) *MockAppFactory_CreateTokenStorer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Configurator
		if args[0] != nil {
			arg0 = args[0].(config.Configurator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppFactory_CreateTokenStorer_Call) Return(tokenStorer auth.TokenStorer, err error) *MockAppFactory_CreateTokenStorer_Call {
	_c.Call.Return(tokenStorer, err)
	return _c
}

func (_c *MockAppFactory_CreateTokenStorer_Call) RunAndReturn(run func(configurator config.Configurator) (auth.TokenStorer, error)) *MockAppFactory_CreateTokenStorer_Call {
	_c.Call.Return(run)
	return _c
}
